udacity/deep-learning

- intro-to-rnns/Anna KaRNNa.ipynb
> Fix typo in notebook

- image-classification/problem_unittests.py
I would remove the `return` from this function definition.
In Python 2, this is a syntax error unless you do a `from __future__ import print_function` before other imports at the top of your file. In Python 3 or in Python 2 in print_function mode, print(x) will always return None.
> Remove extraneous `return`

- language-translation/dlnd_language_translation.ipynb
TensorFlow 1.1 removes sequence to sequence apis used in this project.
> Only allow TensorFlow 1.0 language translation project

- language-translation/helper.py
Different implementations of Python will [do different things](http://blog.lerner.co.il/dont-use-python-close-files-answer-depends/) with files not closed so explicit is better than implicit especially on file writes.
> Use `with open()` to avoid leaking file handles

- gan_mnist/Intro_to_GANs_Exercises.ipynb
The code passes `True` as a 3rd positional argument to `generator()`. It is intended to set `reuse` (which is actually the 4th positional argument), but is actually passed as `n_units`. This results in `n_units` being set to 1 (`True` is implicitly converted to 1 behind the scenes) and `reuse` remaining `False`. This in turn results in an exception during training. The issue was already fixed in the solution notebook, this commit fixes this for the exercise notebook.
> Fix issue with reuse not being properly passed

- tv-script-generation/problem_unittests.py
When using the old unit test, an error will raise.
ValueError: Attempt to reuse RNNCell <tensorflow.contrib.rnn.python.ops.core_rnn_cell_impl.BasicLSTMCell object at 0x0000022C08F13BE0> with a different variable scope than its first use.  First use of cell was with scope 'rnn/multi_rnn_cell/cell_0/basic_lstm_cell', this attempt is with scope 'rnn/multi_rnn_cell/cell_1/basic_lstm_cell'.  Please create a new instance of the cell if you would like it to use a different set of weights.  If before you were using: MultiRNNCell([BasicLSTMCell(...)] * num_layers), change to: MultiRNNCell([BasicLSTMCell(...) for _ in range(num_layers)]).  If before you were using the same cell instance as both the forward and reverse cell of a bidirectional RNN, simply create two instances (one for forward, one …
> Fix unit test, because the behavior of rnn.MultiRNNCell scope changed.

- face_generation/dlnd_face_generation.ipynb
the instructions reference `generator` when they should reference `discriminator`.
> correct a reference to generator in a task description

- language-translation/problem_unittests.py
The assert message wrongly evaluated ```train_decoder_output.get_shape()```, missing ```.rnn_output``` and causing an error instead of printing the assert failure message.
> Fix error in assert message

- tv-script-generation/dlnd_tv_script_generation.ipynb
swaps out "forms" for "forums"
Context: "Train the neural network on the preprocessed data.  If you have a hard time getting a good loss, check the [forms](https://discussions.udacity.com/) to see if anyone is having the same problem."
> docs: tv-script-gen fixes spelling of "forms" to "forums"

- sentiment-rnn/Sentiment_RNN.ipynb
- sentiment-rnn/Sentiment_RNN_Solution.ipynb
Embedding size (`n_words` rows) should allow for an extra entry in the dictionary because 0's are used for padding.
> Sentiment-RNN: Fixed Embedding size

- gan_mnist/Intro_to_GANs_Exercises.ipynb
- gan_mnist/Intro_to_GANs_Solution.ipynb
The generator function calls during training and sampling were using the default parameters. This causes an issue when specifying different hyperparameter values for g_hidden_size and alpha
> Adding n_units and alpha parameters to generator call function

- tv-script-generation/problem_unittests.py
```
initial_state = cell.zero_state(batch_size, tf.float32)
```
returned the following error with TensorFlow 1.2:
```
ValueError: prefix tensor must be either a scalar or vector, but saw
tensor: Tensor("Placeholder:0", dtype=int32)
```
As suggested in udacity/dlnd-issue-reports#334 and tensorflow/tensorflow#10213, it seems we
should use `tf.placeholder(tf.int32, [])` instead.
I've confirmed that the change works for TensorFlow 1.0.
> tv-script-generation: Fix test_get_init_cell for TensorFlow 1.2 (#334)

- gan_mnist/Intro_to_GANs_Exercises.ipynb
Remove `logits` from return doc, since it isn't actually returned.
> GAN_mnist: fix `generator` return doc

- first-neural-network/Your_first_neural_network.ipynb
Github requires widths to be specified in quotes, or else the image isn't rendered. This PR fixes it.
Check here (under `Time to build the network`): [link](https://github.com/udacity/deep-learning/blob/05dbe4136cca84858002e625a977966183f1e992/first-neural-network/Your_first_neural_network.ipynb)
And check the patch: [link](https://github.com/avinassh/deep-learning/blob/patch-1/first-neural-network/Your_first_neural_network.ipynb)
> Fix the image width so that it is rendered properly

- intro-to-tensorflow/environment.yml
See [this](https://github.com/udacity/deep-learning/issues/259) issue for an explanation of why I'm making this PR.
> Locks tf version to fix type error during import

- first-neural-network/Your_first_neural_network.ipynb
The issue of DeprecationWarning can be fixed by replacing .ix with .loc in the following line:
`X, y = train_features.loc[batch].values, train_targets.loc[batch]['cnt']`
> Fixed the DeprecationWarning while training

- image-classification/README.md
Hi Udacity's Team. Here's my update for the `image-classification/README.md`:
- Update job reference(replaced experiment)
- Replace `floyd-command ID` with link to our official docs
Best,
Alessio of FloydHub
> Update floydhub reference for image-classification

- student-admissions/StudentAdmissionsSolutions.ipynb
The Error Term Formula was implemented wrongly and this can confuse students.
> Fix: Correct Error Term Formula Implementation

- language-translation/dlnd_language_translation.ipynb
`decoding_scope` was removed from parameters list to `decoding_layer_infer`.
I'm guessing the markers might still have the old version, based on the feedback I got for my submission.
The assignment can still be completed, in `decoding_layer`, requiring use of `    with tf.variable_scope("decode"):` and `    with tf.variable_scope("decode", reuse=True):`.
> Language Translation: removed zombie comment

- language-translation/dlnd_language_translation.ipynb
Fixed, was `max_summary_length`, corrected to `max_translation_length`
in `decoding_layer_train`
> Lang translation: Fixed name, `max_summary_length`

- intro-to-tflearn/TFLearn_Sentiment_Analysis.ipynb
The `trainY` and `textY` ndarrays were being generated incorrectly due to the values not being passed correctly to `to_categorical`.
> Fix `trainY` and `testY` in Project notebook

- gan_mnist/Intro_to_GANs_Solution.ipynb
The previous code worked in spite of the typo, because the current version of the training code sets up the two tensors to have the same shape.
> gan_mnist: fix label generation for d_loss_fake
