udacity/deep-learning

- intro-to-tflearn/Sentiment Analysis with TFLearn.ipynb
Fixed typos in descriptions of: Output Layer and Testing
> Update Sentiment Analysis with TFLearn.ipynb

- intro-to-rnns/checkpoints/.gitignore
> Create an empty checkpoints folder

- image-classification/dlnd_image_classification.ipynb
> Increased student max accuracy

- .gitignore
a simple gitignore for does of us using Mac.
> gitignore DS_Store

- first-neural-network/DLND Your first neural network.ipynb
According to this Stackoverflow answer http://stackoverflow.com/a/3249684/828184 cite
"The stdout.flush is necessary on some systems, or you won't get any output. Other systems may not require it, but it doesn't do any harm."
> flush added

- tensorboard/Anna KaRNNa.ipynb
As per https://discussions.udacity.com/t/value-error-anna-karnna/230080
> Fix ValueError

- .gitignore
gitignore datasets, and downloaded files.
> gitignore downloaded datasets.

- weight-initialization/weight_initialization.ipynb
Hey guys,
Just a quick typo fix. I really think you meant maxval in the second case (maxval=1.0).
> Change second instance of minval to maxval

- intro-to-tensorflow/intro_to_tensorflow.ipynb
just fixed a typo in the github url
> fixed solutions github url

- language-translation/dlnd_language_translation.ipynb
This pull request correct a few typos in the Project 4 notebook.
> Corrects spelling and grammatical errors

- language-translation/dlnd_language_translation.ipynb
- language-translation/problem_unittests.py
- seq2seq/sequence_to_sequence_implementation.ipynb
Fixes addressing:
- https://github.com/udacity/deep-learning/issues/157
- https://github.com/udacity/dlnd-issue-reports/issues/331
- https://github.com/udacity/dlnd-issue-reports/issues/332
> Project 4 and seq2seq fixes

- seq2seq/sequence_to_sequence_implementation.ipynb
s/source_sentences/target_sentences/
> seq2seq: Make a minor fix to the description of target_sentences

- intro-to-rnns/Anna_KaRNNa.ipynb
- intro-to-rnns/Anna_KaRNNa_Exercises.ipynb
I noticed that if I lost the connection to AWS/Jupyter after some checkpoints were saved, the checkpoints were not reusable, because the vocab mapping changes each time.  This should fix that.
> RNNs Intro - keep vocab mapping stable

- intro-to-tflearn/TFLearn_Sentiment_Analysis_Solution.ipynb
Fixes trainY and testY problem in solution to sentiment analysis example.
> tflearn intro - Fix `trainY` and `testY`

- transfer-learning/Transfer_Learning.ipynb
code is already included in deep-learing.git
(this should also be fixed in lesson instructions')
> don't ask to clone machrisaa/tensorflow-vgg

- student-admissions-keras/StudentAdmissionsKeras.ipynb
the get_dummies function comes from pandas not numpy
> Fixed typo

- sentiment-network/Sentiment_Classification_Projects.ipynb
> Several Typos

- image-classification/dlnd_image_classification.ipynb
> [small] quick grammar on output layer

- sentiment-rnn/Sentiment_RNN.ipynb
- sentiment-rnn/Sentiment_RNN_Solution.ipynb
I found some typos while doing the course, got me confused, then I understood it was a simple typo.
> Fixing typo on Sentiment RNN.

- language-translation/problem_unittests.py
specifically max_target_sequence_length type check message
> language-translation: unit test: fix assertion message

- seq2seq/sequence_to_sequence_implementation.ipynb
Target and source sequence images are reveresed
> Fix little confusing error

- autoencoder/Simple_Autoencoder.ipynb
- autoencoder/Simple_Autoencoder_Solution.ipynb
Before, running this code resulted in an InvalidArgumentError with the message: You must feed a value for placeholder tensor targets
> Added targets to feed dictionary

- transfer-learning/tensorflow_vgg/README.md
Scope of changes is restricted to docs only.
> fix(docs): Corrects typo in project documentation
